// <auto-generated />
using Golfscorecard.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Golfscorecard.DAL.Migrations
{
    [DbContext(typeof(GolfScoreDBContext))]
    partial class GolfScoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Golfscorecard.DAL.Entities.Scorecard", b =>
                {
                    b.Property<int>("ScorecardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScorecardId"), 1L, 1);

                    b.Property<int>("HoleNumber")
                        .HasColumnType("int");

                    b.Property<string>("PlayerFour")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlayerOne")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlayerThree")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlayerTwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ScorecardId");

                    b.ToTable("Scorecards");
                });
#pragma warning restore 612, 618
        }
    }
}
